on: push
name: Build website
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Calculate stats and generate html
        uses: cedrickring/golang-action@1.5.1
        with:
          args: go run ./_repoUtils/main.go
