on: push
name: Build website
jobs:
  build-and-deploy:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false
        run: echo "Branch -->" && git rev-parse --abbrev-ref HEAD

      - name: Calculate stats and generate html
        uses: cedrickring/golang-action@1.5.1
        with:
          args: go run ./_repoUtils/main.go
