on:
  push:
    branches:
      - master
  schedule:
    # every day at 1am
    - cron: "0 1 * * *"
name: Knowledge page
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Calculate stats and generate html
        uses: cedrickring/golang-action@1.5.1
        with:
          args: go run ./_repoUtils/main.go

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./_repoUtils/public
