on: push
name: Build website
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          persist-credentials: false

      - name: Calculate stats and generate html
        uses: cedrickring/golang-action@1.5.1
        with:
          args: go run ./_repoUtils/main.go

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repoUtils/public
